name: Docker Build and Run

on:
  workflow_call:  # Allows this workflow to be called by other workflows

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Cache Docker layers to speed up subsequent builds
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t apache2-image .

      # Step 5: Run the Docker container
      - name: Run Docker container
        run: |
          docker run -d -p 8080:80 apache2-image

      # Step 6: Create README.md in prashantsuk/docker directory with build details
      - name: Create README.md in https://github.com/prashantsuk/docker/tree/main
        run: |
          # Create the directory if it doesn't exist
          mkdir -p prashantsuk/docker

          # Generate current timestamp
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          
          # Create README.md content and save it inside prashantsuk/docker
          echo "# Docker Build Status" > prashantsuk/docker/README.md
          echo "Build Status: SUCCESSFUL" >> prashantsuk/docker/README.md
          echo "Timestamp: $TIMESTAMP" >> prashantsuk/docker/README.md
          echo "Docker Image: apache2-image" >> prashantsuk/docker/README.md
          echo "Port Exposed: 8080" >> prashantsuk/docker/README.md

          # Display the content of the README.md to ensure it's created
          cat prashantsuk/docker/README.md
