name: Trigger Docker Build and Run

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  use-reusable-workflow:
    uses: ./.github/workflows/docker-build-and-run.yml
  
