name: Trigger Docker Build and Run

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  use-reusable-workflow:
    uses: /docker/.github/workflow/docker-build-and-run.yml@main
